// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: classifications.sql

package database

import (
	"context"
)

const createClassification = `-- name: CreateClassification :one
INSERT INTO classifications (id, name)
VALUES (
    gen_random_uuid(),
    $1
)
RETURNING id, name
`

func (q *Queries) CreateClassification(ctx context.Context, name string) (Classification, error) {
	row := q.db.QueryRowContext(ctx, createClassification, name)
	var i Classification
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteClassifications = `-- name: DeleteClassifications :exec
DELETE FROM classifications
`

func (q *Queries) DeleteClassifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteClassifications)
	return err
}

const getClassificationByUserName = `-- name: GetClassificationByUserName :one
SELECT id, name FROM classifications
WHERE name = $1
`

func (q *Queries) GetClassificationByUserName(ctx context.Context, name string) (Classification, error) {
	row := q.db.QueryRowContext(ctx, getClassificationByUserName, name)
	var i Classification
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
