// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: drugs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDrug = `-- name: CreateDrug :one
INSERT INTO drugs (id, generic_name, brand_name, classification_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
RETURNING id, generic_name, brand_name, classification_id
`

type CreateDrugParams struct {
	GenericName      string
	BrandName        string
	ClassificationID uuid.UUID
}

func (q *Queries) CreateDrug(ctx context.Context, arg CreateDrugParams) (Drug, error) {
	row := q.db.QueryRowContext(ctx, createDrug, arg.GenericName, arg.BrandName, arg.ClassificationID)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.GenericName,
		&i.BrandName,
		&i.ClassificationID,
	)
	return i, err
}

const deleteDrugs = `-- name: DeleteDrugs :exec
DELETE FROM drugs
`

func (q *Queries) DeleteDrugs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDrugs)
	return err
}

const getDrugByGenericName = `-- name: GetDrugByGenericName :one
SELECT id, generic_name, brand_name, classification_id FROM drugs
WHERE generic_name = $1
`

func (q *Queries) GetDrugByGenericName(ctx context.Context, genericName string) (Drug, error) {
	row := q.db.QueryRowContext(ctx, getDrugByGenericName, genericName)
	var i Drug
	err := row.Scan(
		&i.ID,
		&i.GenericName,
		&i.BrandName,
		&i.ClassificationID,
	)
	return i, err
}

const listDrugsByClassification = `-- name: ListDrugsByClassification :many
SELECT drugs.id, drugs.generic_name, drugs.brand_name, drugs.classification_id, classifications.name
FROM drugs
JOIN classifications ON drugs.classification_id = classifications.id
ORDER BY classifications.name
`

type ListDrugsByClassificationRow struct {
	Drug Drug
	Name string
}

func (q *Queries) ListDrugsByClassification(ctx context.Context) ([]ListDrugsByClassificationRow, error) {
	rows, err := q.db.QueryContext(ctx, listDrugsByClassification)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDrugsByClassificationRow
	for rows.Next() {
		var i ListDrugsByClassificationRow
		if err := rows.Scan(
			&i.Drug.ID,
			&i.Drug.GenericName,
			&i.Drug.BrandName,
			&i.Drug.ClassificationID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
