// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Classification struct {
	ID   string
	Name string
}

type Drug struct {
	ID               string
	GenericName      string
	BrandName        string
	ClassificationID string
}

type Question struct {
	ID               string
	ClassificationID string
	DrugID           string
	Text             string
	Choice1          string
	Choice2          string
	Choice3          string
	Choice4          string
	Explanation      string
	AnswerIndex      int64
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Session struct {
	ID            string
	UserID        string
	Question1     string
	Question2     string
	Question3     string
	Question4     string
	Question5     string
	Score         int64
	QuestionIndex int64
}

type User struct {
	ID             string
	UserName       string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastDaily      sql.NullTime
	Streak         int64
}
