// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Classification struct {
	ID   uuid.UUID
	Name string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	UserName       string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastDaily      sql.NullTime
	Streak         int32
}
