// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package database

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, question_1, question_2, question_3, question_4, question_5, score, question_index)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    0,
    0
)
RETURNING id, user_id, question_1, question_2, question_3, question_4, question_5, score, question_index
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	Question1 string
	Question2 string
	Question3 string
	Question4 string
	Question5 string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Question1,
		arg.Question2,
		arg.Question3,
		arg.Question4,
		arg.Question5,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question1,
		&i.Question2,
		&i.Question3,
		&i.Question4,
		&i.Question5,
		&i.Score,
		&i.QuestionIndex,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, userID)
	return err
}

const getSessionByUserID = `-- name: GetSessionByUserID :one
SELECT id, user_id, question_1, question_2, question_3, question_4, question_5, score, question_index FROM sessions
WHERE user_id = ?
`

func (q *Queries) GetSessionByUserID(ctx context.Context, userID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserID, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question1,
		&i.Question2,
		&i.Question3,
		&i.Question4,
		&i.Question5,
		&i.Score,
		&i.QuestionIndex,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET score = ?, 
question_index = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	Score         int64
	QuestionIndex int64
	ID            string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession, arg.Score, arg.QuestionIndex, arg.ID)
	return err
}
