-- +goose Up
CREATE TABLE users(
    id TEXT PRIMARY KEY NOT NULL,
    user_name TEXT UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_daily TIMESTAMP DEFAULT NULL,
    streak INT DEFAULT 0 NOT NULL 
);

-- +goose Down
DROP TABLE users;